name: Sync to Mirror

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-hashes-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add mirror remote (with token)
        shell: bash
        env:
          MIRROR_URL: ${{ vars.CNB_URL }}
          MIRROR_TOKEN: ${{ vars.CNB_TOKEN }}
        run: |
          AUTH_URL=$(echo "$MIRROR_URL" | sed -E "s#^https://#https://x-access-token:${MIRROR_TOKEN}@#")
          git remote remove mirror 2>/dev/null || true
          git remote add mirror "$AUTH_URL"

      - name: Push all branches and tags
        shell: bash
        run: |
          git push mirror --all --force
          git push mirror --tags --force